class_name Constants

enum CATEGORY {MATERIAL, REAGENT, POTION, UPGRADE}
enum TYPE {HEALTH, MANA, STAMINA, UPGRADE_REFINE, UPGRADE_DISTILL}
enum ALLOW_UPGRADE {NONE, ANY, REFINE, DISTILL}
enum ID {HERB_HEALTH, HERB_MANA, DUST_HEALTH, DUST_MANA, POTION_HEALTH, POTION_MANA, POTION_STAMINA,
		UPGRADE_REFINE, UPGRADE_DISTILL}
enum EVENT_TYPE {INFO, ADD_CARD, ADJUST_TAX, ADD_REQUEST}
enum BOTTLE_COLOUR {GREEN, BLUE, YELLOW}
